version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wazzap_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wazzap_manager
      POSTGRES_USER: wazzap_user
      POSTGRES_PASSWORD: wazzap_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=es_MX.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - wazzap_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wazzap_user -d wazzap_manager"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: wazzap_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - wazzap_network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: "hydra"

  redis:
    image: redis:7-alpine
    container_name: wazzap_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wazzap_network
    command: redis-server --appendonly yes --requirepass redis_password_2024

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  wazzap_network:
    driver: bridge