defaultPortal: default
portals:
  - name: default
    portalId: YOUR_PORTAL_ID
    authType: personalaccesskey
    personalAccessKey: YOUR_PERSONAL_ACCESS_KEY
    env: default
    portalType: standard
    scopes:
      - crm.objects.contacts.read
      - crm.objects.contacts.write
      - crm.objects.companies.read
      - crm.objects.companies.write
      - crm.objects.deals.read
      - crm.objects.deals.write 